// Generated by https://quicktype.io

import { ICost } from "./budget";

export interface WorkData {
    "first-level": string;
    "second-level"?: SecondLevel[];
}

export interface SecondLevel {
    value: string;
    "third-level": ThirdLevel[];
}

export interface ThirdLevel {
    value: string;
    costs: ICost[];
}

